# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.0.3

# NOTE: The namespace sharing for a pod has been modified by the user and is not the same as the
# default settings for kubernetes. This can lead to unexpected behavior when running the generated
# kube yaml in a kubernetes cluster.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod-kafka
  name: pod-kafka-deployment
spec:
  selector:
    matchLabels:
      app: pod-kafka
  template:
    metadata:
      creationTimestamp: "2024-06-03T14:31:18Z"
      labels:
        app: pod-kafka
      name: pod-kafka
    spec:
      containers:
      - name: zookeeper-container
        command:
        - sh
        - -c
        - bin/zookeeper-server-start.sh config/zookeeper.properties
        env:
        - name: LOG_DIR
          value: /tmp/logs
        image: quay.io/strimzi/kafka:0.39.0-kafka-3.6.1

        ports:
        - containerPort: 2181
          hostPort: 2181
        securityContext:
          runAsNonRoot: true
      - name: kafka-container
        command:
        - sh
        - -c
        - bin/kafka-server-start.sh config/server.properties --override listeners=${KAFKA_LISTENERS}
          --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override
          zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}
        env:
        - name: LOG_DIR
          value: /tmp/logs
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://localhost:9092
        image: quay.io/strimzi/kafka:0.39.0-kafka-3.6.1
        ports:
        - containerPort: 9092
          hostPort: 9092
        securityContext:
          runAsNonRoot: true
