---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./pvc.yaml
- ./pod.yaml
- ./svc.yaml
- ./route.yaml

labels:
  - pairs:
      app: librechat-app
    includeTemplates: false

configMapGenerator:
- name: librechat
  files:
  - librechat.yaml
- name: librechat-env
  envs:
    - .env

generatorOptions:
  disableNameSuffixHash: true