---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: librechat

resources:
- ./pvc.yaml
- ./pod.yaml
- ./svc.yaml
- ./route.yaml
- ./librechat-env.yaml

labels:
  - pairs:
      app: librechat-app
    includeTemplates: false

configMapGenerator:
- name: librechat
  files:
  - librechat.yaml

generatorOptions:
  disableNameSuffixHash: true